import * as vscode from 'vscode';
import { PageSummary } from './notionClient';
import { RecentPage } from './recents';

export type SidebarState = {
	authenticated: boolean;
	workspaceName?: string;
	favorites: PageSummary[];
	recents: RecentPage[];
	message?: string;
	settings?: { openInSidebar: boolean; openInFullView: boolean; openExternalInBrowser: boolean };
};

export function getSidebarHtml(webview: vscode.Webview, state: SidebarState): string {
	const nonce = Math.random().toString(36).slice(2);
	const serializedState = JSON.stringify(state).replaceAll('<', '\\u003c');
	return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}';"><style>
*{box-sizing:border-box}body{margin:0;padding:14px 12px;color:var(--vscode-foreground);background:var(--vscode-sideBar-background);font-family:var(--vscode-font-family);font-size:13px}button,input,select,textarea{font:inherit}button{border:0;color:inherit;background:transparent;cursor:pointer;border-radius:3px;padding:6px 8px;text-align:left}button:hover{background:var(--vscode-toolbar-hoverBackground)}.primary{width:100%;background:var(--vscode-button-background);color:var(--vscode-button-foreground);text-align:center;margin:8px 0 16px}.nav{display:grid;grid-template-columns:1fr 1fr;gap:2px;margin-bottom:12px}.nav button{color:var(--vscode-descriptionForeground)}.search{display:flex;gap:6px;border:1px solid var(--vscode-input-border,transparent);background:var(--vscode-input-background);padding:0 8px;border-radius:4px}.search input{min-width:0;width:100%;border:0;outline:0;padding:8px 0;color:var(--vscode-input-foreground);background:transparent}.section-title{color:var(--vscode-descriptionForeground);font-size:11px;text-transform:uppercase;margin:18px 0 6px 4px}.item{display:flex;align-items:center;width:100%;gap:8px}.item .label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1}.meta{color:var(--vscode-descriptionForeground);font-size:11px;margin-left:26px}.status{color:var(--vscode-descriptionForeground);padding:8px 4px}.error{color:var(--vscode-errorForeground)}.page-toolbar{display:flex;gap:6px;margin-bottom:14px}.page-toolbar button{background:var(--vscode-button-secondaryBackground);color:var(--vscode-button-secondaryForeground)}.page-title{font-size:20px;margin:8px 0 18px}.page-content>*{display:block;margin:8px 0}.page-content p{white-space:pre-wrap}.page-content blockquote{border-left:3px solid var(--vscode-textBlockQuote-border);padding:4px 12px;color:var(--vscode-textBlockQuote-foreground)}.page-content pre{background:var(--vscode-textCodeBlock-background);padding:10px;overflow:auto}.page-content hr{border:0;border-top:1px solid var(--vscode-panel-border)}.child-page{color:var(--vscode-textLink-foreground)}.open-code{color:var(--vscode-textLink-foreground);font-size:11px}.title-input,.edit-block textarea{width:100%;color:var(--vscode-input-foreground);background:var(--vscode-input-background);border:1px solid var(--vscode-input-border);padding:7px}.title-input{font-size:18px}.edit-block{margin:10px 0}.edit-block textarea{min-height:52px;resize:vertical}.add-block{display:flex;gap:6px;margin-top:18px;padding-top:10px;border-top:1px solid var(--vscode-panel-border)}.add-block select{flex:1;color:var(--vscode-dropdown-foreground);background:var(--vscode-dropdown-background);border:1px solid var(--vscode-dropdown-border)}
</style></head><body><header><strong>NOTION</strong><button id="refresh">↻</button></header><div id="app"></div><script nonce="${nonce}">
const vscode=acquireVsCodeApi();const state=${serializedState};const app=document.getElementById('app');let currentPage;let results=[];let viewing=false;let editing=false;let saving=false;
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function item(page,favorite){return '<div class="item"><button class="item" data-open-id="'+esc(page.id)+'"><span>'+esc(page.icon||'▱')+'</span><span class="label">'+esc(page.title)+'</span></button><button data-favorite="'+esc(page.id)+'">'+(favorite?'★':'☆')+'</button></div><div class="meta">'+esc(page.kind)+'</div>'}
function render(){if(viewing)return;if(!state.authenticated){app.innerHTML='<p>Connect your Notion workspace to browse pages.</p><button class="primary" id="signIn">Sign in with Notion</button>';return}const fav=state.favorites.length?state.favorites.map(p=>item(p,true)).join(''):'<div class="status">No favorites yet.</div>';const rec=(state.recents||[]).length?state.recents.map(p=>item(p,false)).join(''):'<div class="status">No recently opened pages.</div>';app.innerHTML='<nav class="nav"><button data-section="search">⌕ Search</button><button data-section="favorites">★ Favorites</button><button data-section="recents">◷ Recents</button><button data-section="settings">⚙ Settings</button></nav><div id="section-search"><div class="search">⌕<input id="query" placeholder="Search workspace"></div><div id="results" class="status">Search your workspace.</div></div><div id="section-favorites" hidden>'+fav+'</div><div id="section-recents" hidden><div class="section-title">Recents <button id="clearRecents">Clear</button></div>'+rec+'</div><div id="section-settings" hidden><div class="section-title">Account</div><p>'+esc(state.workspaceName||'Connected to Notion')+'</p><button id="signOut">Sign out</button><div class="section-title">General</div><label><input type="checkbox" data-setting="openInSidebar" '+(state.settings?.openInSidebar!==false?'checked':'')+'> Open pages in sidebar</label><label><input type="checkbox" data-setting="openInFullView" '+(state.settings?.openInFullView?'checked':'')+'> Open pages in full view</label></div>';document.getElementById('query').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.value.trim()){document.getElementById('results').textContent='Searching...';vscode.postMessage({command:'search',query:e.target.value.trim()})}})}
function renderResults(){const el=document.getElementById('results');if(el)el.innerHTML=results.length?results.map(p=>item(p,state.favorites.some(f=>f.id===p.id))).join(''):'<div class="status">No pages found.</div>'}
function renderBlock(block){const text=esc(block.text||'');if(block.type==='divider')return '<hr>';if(block.type==='child_page')return '<button class="child-page" data-open-id="'+esc(block.pageId||block.id)+'">▱ '+text+'</button>';if(block.type==='code')return '<pre><code>'+text+'</code></pre><button class="open-code" data-code="'+esc(block.text||'')+'" data-language="'+esc(block.language||'plaintext')+'">Open in VS Code</button>';if(block.type==='quote')return '<blockquote>'+text+'</blockquote>';if(block.type==='to_do')return '<p>☐ '+text+'</p>';if(block.type==='bulleted_list_item')return '<p>• '+text+'</p>';if(block.type==='numbered_list_item')return '<p>1. '+text+'</p>';if(String(block.type).startsWith('heading_'))return '<h'+block.type.replace('heading_','')+'>'+text+'</h'+block.type.replace('heading_','')+'>';return '<p><strong>'+esc(String(block.type).replaceAll('_',' '))+':</strong> '+text+(block.url?' <a href="'+esc(block.url)+'">Open resource</a>':'')+'</p>'}
function renderBlock(block){const text=esc(block.text||'');if(block.type==='divider')return '<hr>';if(block.type==='child_page')return '<button class="child-page" data-open-id="'+esc(block.pageId||block.id)+'">▱ '+text+'</button>';if(block.type==='code')return '<pre><code>'+text+'</code></pre><button class="open-code" data-code="'+esc(block.text||'')+'" data-language="'+esc(block.language||'plaintext')+'">Open in VS Code</button>';if(block.type==='quote')return '<blockquote>'+text+'</blockquote>';if(block.type==='to_do')return '<p>☐ '+text+'</p>';if(block.type==='bulleted_list_item')return '<p>• '+text+'</p>';if(block.type==='numbered_list_item')return '<p>1. '+text+'</p>';if(String(block.type).startsWith('heading_'))return '<h'+block.type.replace('heading_','')+'>'+text+'</h'+block.type.replace('heading_','')+'>';return '<p>'+text+(block.url?' <a href="'+esc(block.url)+'">Open resource</a>':'')+'</p>'}
function renderPage(page){viewing=true;currentPage=JSON.parse(JSON.stringify(page));editing=false;app.innerHTML='<div class="page-toolbar"><button id="back">← Back</button><button id="edit">Edit</button><button id="fullView" data-open-id="'+esc(page.id)+'">Full View</button><button id="openInNotion" data-open-id="'+esc(page.id)+'" data-open-url="'+esc(page.url||'')+'">Open in Notion</button></div><h2 class="page-title">'+esc(page.title)+'</h2><div class="page-content">'+(page.blocks.length?page.blocks.map(renderBlock).join(''):'<div class="status">This page has no readable content.</div>')+'</div>'}
function renderEdit(){app.innerHTML='<div class="page-toolbar"><button id="cancelEdit">Cancel</button><button id="saveEdit">Save</button></div><input class="title-input" id="editTitle" value="'+esc(currentPage.title)+'"><div class="page-content">'+currentPage.blocks.map(b=>['paragraph','heading_1','heading_2','bulleted_list_item','to_do'].includes(b.type)?'<div class="edit-block"><textarea data-id="'+esc(b.id)+'">'+esc(b.text||'')+'</textarea>'+(b.type==='to_do'?'<label><input type="checkbox" data-check="'+esc(b.id)+'" '+(b.checked?'checked':'')+'> Done</label>':'')+'</div>':renderBlock(b)).join('')+'</div><div class="add-block"><select id="newBlockType"><option value="paragraph">Paragraph</option><option value="heading_1">Heading 1</option><option value="heading_2">Heading 2</option><option value="bulleted_list_item">Bulleted list</option><option value="to_do">To-do</option></select><button id="addBlock">Add Block</button></div>'}
function saveEdit(){if(saving)return;const title=document.getElementById('editTitle').value.trim();if(!title)return;const blocks=currentPage.blocks.map(b=>{const input=document.querySelector('[data-id="'+b.id+'"]');const check=document.querySelector('[data-check="'+b.id+'"]');return input?{...b,text:input.value,checked:check?check.checked:b.checked}:b});saving=true;document.getElementById('saveEdit').textContent='Saving...';vscode.postMessage({command:'savePage',page:{id:currentPage.id,title,blocks}})}
document.addEventListener('click',e=>{const section=e.target.closest('[data-section]');const open=e.target.closest('[data-open-id]');const code=e.target.closest('[data-code]');if(section){['search','favorites','recents','settings'].forEach(n=>{const el=document.getElementById('section-'+n);if(el)el.hidden=n!==section.dataset.section})}if(e.target.id==='signIn')vscode.postMessage({command:'signIn'});else if(e.target.id==='signOut')vscode.postMessage({command:'signOut'});else if(e.target.id==='refresh')vscode.postMessage({command:'refresh'});else if(e.target.id==='clearRecents')vscode.postMessage({command:'clearRecents'});else if(e.target.id==='back'){viewing=false;render();renderResults()}else if(e.target.id==='edit'){editing=true;renderEdit()}else if(e.target.id==='cancelEdit'){editing=false;renderPage(currentPage)}else if(e.target.id==='saveEdit')saveEdit();else if(e.target.id==='addBlock'){const text=prompt('Block text');if(text)vscode.postMessage({command:'addBlock',id:currentPage.id,blockType:document.getElementById('newBlockType').value,text})}else if(e.target.id==='fullView')vscode.postMessage({command:'fullView',id:e.target.dataset.openId});else if(e.target.id==='openInNotion')vscode.postMessage({command:'openInNotion',id:e.target.dataset.openId,url:e.target.dataset.openUrl});else if(code)vscode.postMessage({command:'openCode',code:code.dataset.code,language:code.dataset.language});else if(open)vscode.postMessage({command:'openPage',id:open.dataset.openId});else if(e.target.closest('[data-favorite]'))vscode.postMessage({command:'toggleFavorite',id:e.target.closest('[data-favorite]').dataset.favorite})});
window.addEventListener('message',e=>{const m=e.data;if(m.type==='state'){Object.assign(state,m.state);if(!viewing)render()}if(m.type==='results'){results=m.results;renderResults()}if(m.type==='pageLoading'){app.innerHTML='<div class="status">Loading page...</div>'}if(m.type==='page')renderPage(m.page);if(m.type==='error'){saving=false;app.innerHTML='<div class="status error">'+esc(m.message)+'</div>'}});render();
</script></body></html>`;
}
